apiVersion: v1
kind: Namespace
metadata:
  name: kuadrant-operators
  labels:
    app.kubernetes.io/part-of: rhcl
---
apiVersion: v1
kind: Namespace
metadata:
  name: kuadrant-system
  labels:
    app.kubernetes.io/part-of: rhcl
