FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

RUN microdnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    microdnf install -y python3 python3-configargparse python3-kubernetes && \
    microdnf clean all

COPY llmd_xks_preflight.py /opt/llmd-xks-preflight/

RUN useradd -r -u 1001 -g 0 preflight
USER 1001

ENTRYPOINT ["python3", "/opt/llmd-xks-preflight/llmd_xks_preflight.py"]
