bundle:
  version: v1.15.2
certManager:
  enabled: true
createInfrastructure: true
operandNamespace: cert-manager
operatorNamespace: cert-manager-operator
pullSecret:
  dockerConfigJson: ""
  name: redhat-pull-secret
